### ISSUE TITLE
XRT 2019.1 Installation Issues on Ubuntu Xenail HWE

### ISSUE THREAD

**Issue by kenhill** [Xilinx/XRT#1652]
XRT 2019.1 depends on built-in kernel module `fpga` which is part of the `linux-modules-extra` package. 

Can this be added as a dependency for the XRT `*.deb`

**Comment by uday610** [comment]
@sonals , please check this issue.

**Comment by keryell** [comment]
On my machines `linux-modules-extra` comes with `linux-generic` which is installed by default, but it is on `19.04`, not Xenial `16.04` which is more than 3 year old...
But it does not seem harmful to add the dependency you propose.
Otherwise you could try a newer version, at least 18.04 LTS. You will get not only the support from HWE for new hardware, but everything else. :-)

**Comment by sonals** [comment]
Closing as obsolete.
