### ISSUE TITLE
XRT does not support Boost 1.73.0

### ISSUE THREAD

**Issue by paroque28** [Xilinx/XRT#3756]
XRT fails in compilation:
```
fatal error: boost/  detail/endian.hpp: No such file or directory | #include <boost/detail/endian.hpp>
```
In 1.73.0 some macros and header files were deprecated.
For example:
`BOOST_BYTE_ORDER`
:
```
The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
```

**Comment by stsoe** [comment]
Correct we don't support boost 1.73.0.  A pull request would be greatly appreciated :-)

**Comment by keryell** [comment]
Actually I have the same issue with `Debian/unstable` which comes with 1.71.

**Comment by stsoe** [comment]
I am positive we can build with 1.71, because that is the version used on Ubuntu 20.04.  You will get a deprecation warning but not a hard error.   Regardless this of course needs to be fixed.  The problem is we need to support boost all the way back to 1.53.0 (CentOS7.x), I may just disable the compilation check.

**Comment by stsoe** [comment]
References to endian.hpp were removed
