### ISSUE TITLE
Ubuntu 20.04 and 20.10 Vivado and XRT running well but not supported via installer.

### ISSUE THREAD

**Issue by Zaryob** [Xilinx/XRT#4466]
Hi,

I am using Ubuntu 20.10. before the fresh install I used Vivado and XRT in Ubuntu 18.04 and it was working very well. 

I cannot installed Vivado 2020.2 on Ubuntu 20.10. It just waiting on white screen after first page and in the first page, it says "just listed environments are supported."

I applied that [solution](https://forums.xilinx.com/t5/Installation-and-Licensing/Xilinx-Unified-Installer-2020-1-Exception-in-thread-quot-SPLASH/m-p/1114510#M29451). With giving fake os-release to Ubuntu, it is installed.

After installation it give me that 
```
application-specific initialization failed: couldn't load file "librdi_commontasks.so": libtinfo.so.5: cannot open shared object file: No such file or directory
```

I fixed that issue with installing `libtinfo.so.5` library from [Ubuntu Universe Official Repository](https://ubuntu.pkgs.org/20.10/ubuntu-universe-amd64/)

I recommend you to with next release of Vivado Suite you need to edit installation targets and add next Ubuntu LTS 20.04.

bests.

**Comment by keryell** [comment]
After trying various ways, we reached the recipe https://github.com/triSYCL/sycl/blob/sycl/unified/master/sycl/doc/GettingStartedXilinxFPGA.md#install-vitis-20201 that worked for us for Ubuntu 20.04 & 2020.1. We upgraded the machine to 20.10 and it is still working.
Since we do not have tried 2020.2 yet with the installer on 20.10 from scratch I cannot be sure yet, but as we are skipping the non-working Java graphics part, it might work for you too...

**Comment by stsoe** [comment]
Not an XRT issue.

**Comment by keryell** [comment]
I guess there is a hierarchy of issues.
Working with a work-around while not supported is still great compared to not working at all.
Ping on https://github.com/Xilinx/XRT/issues/5168...
